/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/chick.glb --types 
Author: Rukh3D (https://sketchfab.com/rukh3d)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/chick-baby-chicken-bird-d5844a9e5db74fb59effe632d5f3faa3
Title: Chick Baby Chicken Bird
*/

import * as THREE from 'three'
import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'

type ActionName = 'Armature|Animation'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Object_36: THREE.SkinnedMesh
    _rootJoint: THREE.Bone
  }
  materials: {
    chicken: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: React.JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>(null)
  const { scene, animations } = useGLTF('/models/chick.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as any
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="4ca55330a8ae4c7b982346cd0ab93b7cfbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Armature" scale={100}>
                  <group name="Object_5">
                    <primitive object={nodes._rootJoint} />
                    <group name="Object_35" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <skinnedMesh name="Object_36" geometry={nodes.Object_36.geometry} material={materials.chicken} skeleton={nodes.Object_36.skeleton} />
                  </group>
                </group>
                <group name="CR_1044a_rig" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/chick.glb')

// Animation wrapper component for enhanced model interactions
export function AnimatedModel({
  children,
  autoPlay = true,
  onClick,
  ...props
}: {
  children: React.ReactNode;
  autoPlay?: boolean;
  onClick?: () => void;
} & React.JSX.IntrinsicElements['group']) {
  const groupRef = React.useRef<THREE.Group>(null);

  return (
    <group
      ref={groupRef}
      onClick={onClick}
      {...props}
    >
      {children}
    </group>
  );
}
