/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Chicken.glb --types -o src/app/components/models/LargeChickenModelGen.tsx 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    node_id53: THREE.Mesh
  }
  materials: {
    ['75']: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationClip[]
}

export function Model(props: React.JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Chicken.glb') as any
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.node_id53.geometry} material={materials['75']} position={[0, -0.252, 0.256]} rotation={[0, 1.33, 0]} scale={0.132} />
    </group>
  )
}

useGLTF.preload('/Chicken.glb')
