/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

'use client'

import { useGLTF } from '@react-three/drei'

// 3D Model from: Static chicken model
interface StaticChickenProps {
  [key: string]: unknown;
}

export function StaticChicken(props: StaticChickenProps) {
  const { nodes, materials } = useGLTF('/3d/static-chicken.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={(nodes as any).node_id53.geometry}
        material={materials['75']}
        position={[0, -0.252, 0.256]}
        rotation={[0, 1.33, 0]}
        scale={0.132}
      />
    </group>
  )
}

useGLTF.preload('/3d/static-chicken.glb')


